name: release
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api
            dockerfile: ./services/api/Dockerfile
          - name: projects
            dockerfile: ./services/projects/Dockerfile
          - name: teams
            dockerfile: ./services/teams/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Lowercase owner
        shell: bash
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/buildaxis-auth-${{ matrix.name }}:${{ github.ref_name }}
