name: release
on:
  push:
    tags:
<<<<<<< HEAD
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
=======
      - 'v*.*.*'   # run on semver tags

permissions:
  contents: write   # needed for GitHub Release
  packages: write   # needed to push to GHCR
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)

jobs:
  docker-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - id: meta
=======
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Derive TAG and owner (lowercased for GHCR)
        id: meta
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
        shell: bash
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"
          echo "repo_name=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_OUTPUT"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

<<<<<<< HEAD
      - uses: docker/login-action@v3
=======
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

<<<<<<< HEAD
      - uses: actions/cache@v4
=======
      # Optional: load build cache to speed up builds
      - name: Prepare cache
        uses: actions/cache@v4
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

<<<<<<< HEAD
      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
=======
      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # If you only need linux/amd64, drop platforms to just that.
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.repo_name }}:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/${{ steps.meta.outputs.repo_name }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ steps.meta.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

<<<<<<< HEAD
      - if: always()
=======
      - name: Move cache
        if: always()
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

<<<<<<< HEAD
      - uses: softprops/action-gh-release@v2
=======
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
>>>>>>> 2f7dd58 (ci: GHCR docker release on tag + GH Release)
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.tag }}
          generate_release_notes: true
