name: release
on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api
            dockerfile: ./services/api/Dockerfile
          - name: projects
            dockerfile: ./services/projects/Dockerfile
          - name: teams
            dockerfile: ./services/teams/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Set NS (lowercase owner for GHCR)
        run: echo "NS=ghcr.io/${{ toLower(github.repository_owner) }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          # tag uses LOWERCASED owner via $NS
          tags: |
            ${{ env.NS }}/buildaxis-auth-${{ matrix.name }}:${{ github.ref_name }}
          # keep simple; you already do cosign separately
          provenance: false
          sbom: false
