name: release

on:
  push:
    tags:
      - 'v*.*.*'   # semver tags

permissions:
  contents: write   # for GitHub Release
  packages: write   # for GHCR push

jobs:
  publish:
    name: publish (${{ matrix.name }}, ${{ matrix.dockerfile }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: api,      dockerfile: services/api/Dockerfile,      suffix: -api }
          - { name: projects, dockerfile: services/projects/Dockerfile,  suffix: -projects }
          - { name: teams,    dockerfile: services/teams/Dockerfile,     suffix: -teams }

    env:
      BUILDKIT_PROGRESS: plain

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Vars (tag/owner)
        id: vars
        shell: bash
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          echo "owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.vars.outputs.owner_lc }}/buildaxis-auth${{ matrix.suffix }}
          tags: |
            type=raw,value=${{ steps.vars.outputs.tag }}
            type=raw,value=latest

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

  release-note:
    name: GitHub Release
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Vars
        id: vars
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          generate_release_notes: true
