name: release
on:
  push:
    tags: ['v*']
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  ORG: ${{ github.repository_owner }}
  TAG: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images (compose)
        run: docker compose build

      - name: Tag images for GHCR
        run: |
          for svc in api projects teams; do
            src="buildaxis-auth-$svc"
            dst="${REGISTRY}/${ORG}/buildaxis-auth-$svc"
            docker tag "$src" "$dst:${TAG}"
            docker tag "$src" "$dst:latest"
          done

      - name: Push images
        run: |
          for svc in api projects teams; do
            repo="${REGISTRY}/${ORG}/buildaxis-auth-$svc"
            docker push "$repo:${TAG}"
            docker push "$repo:latest"
          done
