name: smoke
on: [push, pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose up -d --build
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: chmod +x scripts/smoke.sh
      - run: ./scripts/smoke.sh
